version: '3'
services:
  d2e-frontend:
    build: .
    ports:
      - "8080:8080"
    container_name: d2e-frontend
    volumes:
       - node_modules:/app/node_modules
       - ".:/app"


volumes:
  node_modules:
