version: '3'
services:
  # nodejs-server:
  #   build:
  #     context: ./api
  #     dockerfile: Dockerfile-dev
  #   ports:
  #     - "3080:3080"
  #   container_name: node-api
  #   volumes:
  #      - ./api:/usr/src/app/api
  #      - /usr/src/app/api/node_modules
       
  d2e-frontend:
    build: .
    ports:
      - "8080:8080"
    container_name: d2e-frontend
    volumes:
       - node_modules:/app/node_modules
       - ".:/app"


volumes:
  node_modules:
