FROM node:14-slim as build-stage

WORKDIR /app

RUN apt update && apt install g++ build-essential git -y

RUN npm i -D @storybook/cli

COPY package*.json ./

RUN npm install

# copie les fichiers et dossiers du projet dans le dossier de travail (par exemple : le dossier 'app')
COPY . .

EXPOSE 6006

CMD ["npm", "run", "storybook"]