version: '3'
services:
  d2e-frontend:
    build: .
    ports:
      - "8080:8080"
    container_name: d2e-frontend
    volumes:
       - node_modules:/app/node_modules
       - ".:/app"
  
  d2e-storybook:
    build: .
    command: npm run storybook
    container_name: d2e-storybook
    volumes:
       - node_modules:/app/node_modules
       - ".:/app"
    ports:
      - 6006:6006



volumes:
  node_modules:
