version: '3'
services:
  d2e-frontend:
    build: .
    ports:
      - "8080:8080"
    container_name: d2e-frontend
    volumes:
       - "./src:/app/src"
       - "./public:/app/public"
  
  d2e-storybook:
    build: 
      context: .
      dockerfile: .ci/master/Dockerfile.storybook
    container_name: d2e-storybook
    volumes:
       - "./src:/app/src"
    ports:
      - 6006:6006



volumes:
  node_modules:
