# étape de build
FROM node:14-slim as build-stage
WORKDIR /app


RUN apt update && apt install g++ build-essential git -y

RUN npm i -D @storybook/cli

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build-storybook

# étape de production
FROM nginx:stable-alpine as production-stage
COPY --from=build-stage /app/storybook-static /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]